# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
    - title: My Pull Requests
      filters: is:open author:@me
    - title: Needs Review
      filters: is:open review-requested:@me -is:draft
    - title: Involved
      filters: is:open reviewed-by:@me -author:@me
issuesSections:
    - title: My Issues
      filters: is:open author:@me
    - title: Assigned
      filters: is:open assignee:@me
    - title: Involved
      filters: is:open involves:@me -author:@me
notificationsSections:
    - title: Review Follow-up
      filters: is:unread reason:participating
    - title: All
      filters: ""
    - title: Created
      filters: reason:author
    - title: Participating
      filters: reason:participating
    - title: Mentioned
      filters: reason:mention
    - title: Review Requested
      filters: reason:review-requested
    - title: Assigned
      filters: reason:assign
    - title: Subscribed
      filters: reason:subscribed
    - title: Team Mentioned
      filters: reason:team-mention
repo:
    branchesRefetchIntervalSeconds: 30
    prsRefetchIntervalSeconds: 60
defaults:
    preview:
        open: true
        width: 0.45
    prsLimit: 20
    prApproveComment: LGTM
    issuesLimit: 20
    notificationsLimit: 20
    view: prs
    layout:
        prs:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 20
            author:
                width: 15
            authorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
            base:
                width: 15
                hidden: true
            lines:
                width: 15
        issues:
            updatedAt:
                width: 5
            createdAt:
                width: 5
            repo:
                width: 15
            creator:
                width: 10
            creatorIcon:
                hidden: false
            assignees:
                width: 20
                hidden: true
    refetchIntervalMinutes: 30
keybindings:
    prs:
        - key: ctrl+g
          name: review in tuicr
          command: tuicr pr {{.RepoName}}#{{.PrNumber}}
repoPaths: {}
theme:
    ui:
        sectionsShowCount: true
        table:
            showSeparators: true
            compact: false
    colors:
        text:
            primary: "#cad3f5"
            secondary: "#cad3f5"
            inverted: "#24273a"
            faint: "#939ab7"
            warning: "#ed8796"
            success: "#a6da95"
            actor: "#b8c0e0"
        background:
            selected: "#494d64"
        border:
            primary: "#8aadf4"
            secondary: "#5b6078"
            faint: "#494d64"
    pager:
    diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
includeReadNotifications: true
